/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { EmailConfirmationRequest } from '../../models/email-confirmation-request';
import { EmailConfirmationResponse } from '../../models/email-confirmation-response';

export interface ConfirmEmailAuthConfirmEmailPost$Params {
      body: EmailConfirmationRequest
}

export function confirmEmailAuthConfirmEmailPost(http: HttpClient, rootUrl: string, params: ConfirmEmailAuthConfirmEmailPost$Params, context?: HttpContext): Observable<StrictHttpResponse<EmailConfirmationResponse>> {
  const rb = new RequestBuilder(rootUrl, confirmEmailAuthConfirmEmailPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<EmailConfirmationResponse>;
    })
  );
}

confirmEmailAuthConfirmEmailPost.PATH = '/auth/confirm-email';
