/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { WalletNonceRequest } from '../../models/wallet-nonce-request';
import { WalletNonceResponse } from '../../models/wallet-nonce-response';

export interface CreateWalletNonceAuthWalletNoncePost$Params {
      body: WalletNonceRequest
}

export function createWalletNonceAuthWalletNoncePost(http: HttpClient, rootUrl: string, params: CreateWalletNonceAuthWalletNoncePost$Params, context?: HttpContext): Observable<StrictHttpResponse<WalletNonceResponse>> {
  const rb = new RequestBuilder(rootUrl, createWalletNonceAuthWalletNoncePost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<WalletNonceResponse>;
    })
  );
}

createWalletNonceAuthWalletNoncePost.PATH = '/auth/wallet/nonce';
