/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PagedSmartContractEventResponse } from '../../models/paged-smart-contract-event-response';

export interface ListEventsSmartContractEventsGet$Params {
  page_index?: number;
  page_size?: number;
}

export function listEventsSmartContractEventsGet(http: HttpClient, rootUrl: string, params?: ListEventsSmartContractEventsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<PagedSmartContractEventResponse>> {
  const rb = new RequestBuilder(rootUrl, listEventsSmartContractEventsGet.PATH, 'get');
  if (params) {
    rb.query('page_index', params.page_index, {});
    rb.query('page_size', params.page_size, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PagedSmartContractEventResponse>;
    })
  );
}

listEventsSmartContractEventsGet.PATH = '/smart-contract-events';
