/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MintAllowTokenRequest } from '../../models/mint-allow-token-request';
import { MintAllowTokenResponse } from '../../models/mint-allow-token-response';

export interface CheckMintLotteryCheckMintPost$Params {
      body: MintAllowTokenRequest
}

export function checkMintLotteryCheckMintPost(http: HttpClient, rootUrl: string, params: CheckMintLotteryCheckMintPost$Params, context?: HttpContext): Observable<StrictHttpResponse<MintAllowTokenResponse>> {
  const rb = new RequestBuilder(rootUrl, checkMintLotteryCheckMintPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<MintAllowTokenResponse>;
    })
  );
}

checkMintLotteryCheckMintPost.PATH = '/lottery/check-mint';
