/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateLotteryRequest } from '../../models/create-lottery-request';
import { LotteryResponse } from '../../models/lottery-response';

export interface CreateLotteryLotteryCreatePost$Params {
  allow_existing?: boolean;
      body: CreateLotteryRequest
}

export function createLotteryLotteryCreatePost(http: HttpClient, rootUrl: string, params: CreateLotteryLotteryCreatePost$Params, context?: HttpContext): Observable<StrictHttpResponse<LotteryResponse>> {
  const rb = new RequestBuilder(rootUrl, createLotteryLotteryCreatePost.PATH, 'post');
  if (params) {
    rb.query('allow_existing', params.allow_existing, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<LotteryResponse>;
    })
  );
}

createLotteryLotteryCreatePost.PATH = '/lottery/create';
