/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CoinChartResponse } from '../../models/coin-chart-response';

export interface GetCoinChartLotteryCoinMintChartGet$Params {
  mint: string;
}

export function getCoinChartLotteryCoinMintChartGet(http: HttpClient, rootUrl: string, params: GetCoinChartLotteryCoinMintChartGet$Params, context?: HttpContext): Observable<StrictHttpResponse<CoinChartResponse>> {
  const rb = new RequestBuilder(rootUrl, getCoinChartLotteryCoinMintChartGet.PATH, 'get');
  if (params) {
    rb.path('mint', params.mint, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CoinChartResponse>;
    })
  );
}

getCoinChartLotteryCoinMintChartGet.PATH = '/lottery/coin/{mint}/chart';
