/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BetParticipationResponse } from '../../models/bet-participation-response';

export interface GetLotteryBetsLotteryLotteryIdBetsGet$Params {
  lottery_id: number;
}

export function getLotteryBetsLotteryLotteryIdBetsGet(http: HttpClient, rootUrl: string, params: GetLotteryBetsLotteryLotteryIdBetsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<BetParticipationResponse>>> {
  const rb = new RequestBuilder(rootUrl, getLotteryBetsLotteryLotteryIdBetsGet.PATH, 'get');
  if (params) {
    rb.path('lottery_id', params.lottery_id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<BetParticipationResponse>>;
    })
  );
}

getLotteryBetsLotteryLotteryIdBetsGet.PATH = '/lottery/{lottery_id}/bets';
