/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { LotteryArchiveListResponse } from '../../models/lottery-archive-list-response';

export interface GetLotteryArchiveLotteryArchiveGet$Params {

/**
 * Lottery type: pumpfun or dex
 */
  lottery_type?: string;

/**
 * Show rounds where nobody committed anything
 */
  include_empty?: boolean;
  window_days?: number;
}

export function getLotteryArchiveLotteryArchiveGet(http: HttpClient, rootUrl: string, params?: GetLotteryArchiveLotteryArchiveGet$Params, context?: HttpContext): Observable<StrictHttpResponse<LotteryArchiveListResponse>> {
  const rb = new RequestBuilder(rootUrl, getLotteryArchiveLotteryArchiveGet.PATH, 'get');
  if (params) {
    rb.query('lottery_type', params.lottery_type, {});
    rb.query('include_empty', params.include_empty, {});
    rb.query('window_days', params.window_days, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<LotteryArchiveListResponse>;
    })
  );
}

getLotteryArchiveLotteryArchiveGet.PATH = '/lottery/archive';
