/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { LotteryCycleControlsResponse } from '../../models/lottery-cycle-controls-response';

export interface GetLotteryCyclesLotteryCyclesGet$Params {
}

export function getLotteryCyclesLotteryCyclesGet(http: HttpClient, rootUrl: string, params?: GetLotteryCyclesLotteryCyclesGet$Params, context?: HttpContext): Observable<StrictHttpResponse<LotteryCycleControlsResponse>> {
  const rb = new RequestBuilder(rootUrl, getLotteryCyclesLotteryCyclesGet.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<LotteryCycleControlsResponse>;
    })
  );
}

getLotteryCyclesLotteryCyclesGet.PATH = '/lottery/cycles';
