/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MyCommitsResponse } from '../../models/my-commits-response';

export interface GetMyCommitsLotteryMyCommitsGet$Params {
}

export function getMyCommitsLotteryMyCommitsGet(http: HttpClient, rootUrl: string, params?: GetMyCommitsLotteryMyCommitsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<MyCommitsResponse>> {
  const rb = new RequestBuilder(rootUrl, getMyCommitsLotteryMyCommitsGet.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<MyCommitsResponse>;
    })
  );
}

getMyCommitsLotteryMyCommitsGet.PATH = '/lottery/my/commits';
