/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PurchaseFeedResponse } from '../../models/purchase-feed-response';

export interface GetLotteryPurchasesLotteryLotteryIdPurchasesGet$Params {
  lottery_id: number;
}

export function getLotteryPurchasesLotteryLotteryIdPurchasesGet(http: HttpClient, rootUrl: string, params: GetLotteryPurchasesLotteryLotteryIdPurchasesGet$Params, context?: HttpContext): Observable<StrictHttpResponse<PurchaseFeedResponse>> {
  const rb = new RequestBuilder(rootUrl, getLotteryPurchasesLotteryLotteryIdPurchasesGet.PATH, 'get');
  if (params) {
    rb.path('lottery_id', params.lottery_id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PurchaseFeedResponse>;
    })
  );
}

getLotteryPurchasesLotteryLotteryIdPurchasesGet.PATH = '/lottery/{lottery_id}/purchases';
