/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { LotteryEntryResponse } from '../../models/lottery-entry-response';

export interface GetLotteryEntryByCoinLotteryCoinCoinNameGet$Params {
  coin_name: string;
}

export function getLotteryEntryByCoinLotteryCoinCoinNameGet(http: HttpClient, rootUrl: string, params: GetLotteryEntryByCoinLotteryCoinCoinNameGet$Params, context?: HttpContext): Observable<StrictHttpResponse<LotteryEntryResponse>> {
  const rb = new RequestBuilder(rootUrl, getLotteryEntryByCoinLotteryCoinCoinNameGet.PATH, 'get');
  if (params) {
    rb.path('coin_name', params.coin_name, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<LotteryEntryResponse>;
    })
  );
}

getLotteryEntryByCoinLotteryCoinCoinNameGet.PATH = '/lottery/coin/{coin_name}';
