/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { LotteryResponse } from '../../models/lottery-response';

export interface MarkVrfBindedLotteryLotteryIdVrfBindedPost$Params {
  lottery_id: number;
}

export function markVrfBindedLotteryLotteryIdVrfBindedPost(http: HttpClient, rootUrl: string, params: MarkVrfBindedLotteryLotteryIdVrfBindedPost$Params, context?: HttpContext): Observable<StrictHttpResponse<LotteryResponse>> {
  const rb = new RequestBuilder(rootUrl, markVrfBindedLotteryLotteryIdVrfBindedPost.PATH, 'post');
  if (params) {
    rb.path('lottery_id', params.lottery_id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<LotteryResponse>;
    })
  );
}

markVrfBindedLotteryLotteryIdVrfBindedPost.PATH = '/lottery/{lottery_id}/vrf-binded';
