/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Phase2AccountsResponse } from '../../models/phase-2-accounts-response';

export interface Phase2AccountsLotteryLotteryIdPhase2AccountsGet$Params {
  lottery_id: number;
}

export function phase2AccountsLotteryLotteryIdPhase2AccountsGet(http: HttpClient, rootUrl: string, params: Phase2AccountsLotteryLotteryIdPhase2AccountsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Phase2AccountsResponse>> {
  const rb = new RequestBuilder(rootUrl, phase2AccountsLotteryLotteryIdPhase2AccountsGet.PATH, 'get');
  if (params) {
    rb.path('lottery_id', params.lottery_id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Phase2AccountsResponse>;
    })
  );
}

phase2AccountsLotteryLotteryIdPhase2AccountsGet.PATH = '/lottery/{lottery_id}/phase2-accounts';
