/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BetParticipationResponse } from '../../models/bet-participation-response';
import { CreateBetRequest } from '../../models/create-bet-request';

export interface PlaceBetLotteryBetPost$Params {
      body: CreateBetRequest
}

export function placeBetLotteryBetPost(http: HttpClient, rootUrl: string, params: PlaceBetLotteryBetPost$Params, context?: HttpContext): Observable<StrictHttpResponse<BetParticipationResponse>> {
  const rb = new RequestBuilder(rootUrl, placeBetLotteryBetPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<BetParticipationResponse>;
    })
  );
}

placeBetLotteryBetPost.PATH = '/lottery/bet';
