/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Phase2PrepareResponse } from '../../models/phase-2-prepare-response';

export interface PreparePhase2LotteryLotteryIdPhase2PreparePost$Params {
  lottery_id: number;
}

export function preparePhase2LotteryLotteryIdPhase2PreparePost(http: HttpClient, rootUrl: string, params: PreparePhase2LotteryLotteryIdPhase2PreparePost$Params, context?: HttpContext): Observable<StrictHttpResponse<Phase2PrepareResponse>> {
  const rb = new RequestBuilder(rootUrl, preparePhase2LotteryLotteryIdPhase2PreparePost.PATH, 'post');
  if (params) {
    rb.path('lottery_id', params.lottery_id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Phase2PrepareResponse>;
    })
  );
}

preparePhase2LotteryLotteryIdPhase2PreparePost.PATH = '/lottery/{lottery_id}/phase2-prepare';
