/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Phase2RequestRandomnessResponse } from '../../models/phase-2-request-randomness-response';

export interface RequestPhase2RandomnessLotteryLotteryIdPhase2RequestRandomnessPost$Params {
  lottery_id: number;
}

export function requestPhase2RandomnessLotteryLotteryIdPhase2RequestRandomnessPost(http: HttpClient, rootUrl: string, params: RequestPhase2RandomnessLotteryLotteryIdPhase2RequestRandomnessPost$Params, context?: HttpContext): Observable<StrictHttpResponse<Phase2RequestRandomnessResponse>> {
  const rb = new RequestBuilder(rootUrl, requestPhase2RandomnessLotteryLotteryIdPhase2RequestRandomnessPost.PATH, 'post');
  if (params) {
    rb.path('lottery_id', params.lottery_id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Phase2RequestRandomnessResponse>;
    })
  );
}

requestPhase2RandomnessLotteryLotteryIdPhase2RequestRandomnessPost.PATH = '/lottery/{lottery_id}/phase2-request-randomness';
