/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Phase2RevealRequest } from '../../models/phase-2-reveal-request';
import { Phase2RevealResponse } from '../../models/phase-2-reveal-response';

export interface RevealPhase2RandomnessLotteryLotteryIdPhase2RevealPost$Params {
  lottery_id: number;
      body: Phase2RevealRequest
}

export function revealPhase2RandomnessLotteryLotteryIdPhase2RevealPost(http: HttpClient, rootUrl: string, params: RevealPhase2RandomnessLotteryLotteryIdPhase2RevealPost$Params, context?: HttpContext): Observable<StrictHttpResponse<Phase2RevealResponse>> {
  const rb = new RequestBuilder(rootUrl, revealPhase2RandomnessLotteryLotteryIdPhase2RevealPost.PATH, 'post');
  if (params) {
    rb.path('lottery_id', params.lottery_id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Phase2RevealResponse>;
    })
  );
}

revealPhase2RandomnessLotteryLotteryIdPhase2RevealPost.PATH = '/lottery/{lottery_id}/phase2-reveal';
