/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { RunPurchasesResponse } from '../../models/run-purchases-response';

export interface RunPurchasesLotteryLotteryIdRunPurchasesPost$Params {
  lottery_id: number;
}

export function runPurchasesLotteryLotteryIdRunPurchasesPost(http: HttpClient, rootUrl: string, params: RunPurchasesLotteryLotteryIdRunPurchasesPost$Params, context?: HttpContext): Observable<StrictHttpResponse<RunPurchasesResponse>> {
  const rb = new RequestBuilder(rootUrl, runPurchasesLotteryLotteryIdRunPurchasesPost.PATH, 'post');
  if (params) {
    rb.path('lottery_id', params.lottery_id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<RunPurchasesResponse>;
    })
  );
}

runPurchasesLotteryLotteryIdRunPurchasesPost.PATH = '/lottery/{lottery_id}/run-purchases';
