/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { RunPurchasesPayload } from '../../models/run-purchases-payload';

export interface RunPurchasesPayloadPreviewLotteryLotteryIdRunPurchasesPayloadGet$Params {
  lottery_id: number;
}

export function runPurchasesPayloadPreviewLotteryLotteryIdRunPurchasesPayloadGet(http: HttpClient, rootUrl: string, params: RunPurchasesPayloadPreviewLotteryLotteryIdRunPurchasesPayloadGet$Params, context?: HttpContext): Observable<StrictHttpResponse<RunPurchasesPayload>> {
  const rb = new RequestBuilder(rootUrl, runPurchasesPayloadPreviewLotteryLotteryIdRunPurchasesPayloadGet.PATH, 'get');
  if (params) {
    rb.path('lottery_id', params.lottery_id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<RunPurchasesPayload>;
    })
  );
}

runPurchasesPayloadPreviewLotteryLotteryIdRunPurchasesPayloadGet.PATH = '/lottery/{lottery_id}/run-purchases-payload';
