/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { LotteryCycleControlResponse } from '../../models/lottery-cycle-control-response';

export interface StopLotteryCycleLotteryCyclesLotteryTypeStopPost$Params {
  lottery_type: string;
}

export function stopLotteryCycleLotteryCyclesLotteryTypeStopPost(http: HttpClient, rootUrl: string, params: StopLotteryCycleLotteryCyclesLotteryTypeStopPost$Params, context?: HttpContext): Observable<StrictHttpResponse<LotteryCycleControlResponse>> {
  const rb = new RequestBuilder(rootUrl, stopLotteryCycleLotteryCyclesLotteryTypeStopPost.PATH, 'post');
  if (params) {
    rb.path('lottery_type', params.lottery_type, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<LotteryCycleControlResponse>;
    })
  );
}

stopLotteryCycleLotteryCyclesLotteryTypeStopPost.PATH = '/lottery/cycles/{lottery_type}/stop';
