/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { VrfPreviewResponse } from '../../models/vrf-preview-response';

export interface VrfPreviewLotteryLotteryIdVrfPreviewGet$Params {
  lottery_id: number;
}

export function vrfPreviewLotteryLotteryIdVrfPreviewGet(http: HttpClient, rootUrl: string, params: VrfPreviewLotteryLotteryIdVrfPreviewGet$Params, context?: HttpContext): Observable<StrictHttpResponse<VrfPreviewResponse>> {
  const rb = new RequestBuilder(rootUrl, vrfPreviewLotteryLotteryIdVrfPreviewGet.PATH, 'get');
  if (params) {
    rb.path('lottery_id', params.lottery_id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<VrfPreviewResponse>;
    })
  );
}

vrfPreviewLotteryLotteryIdVrfPreviewGet.PATH = '/lottery/{lottery_id}/vrf-preview';
