/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ChatMessageResponse } from '../../models/chat-message-response';

export interface GetChatMessageChatsChatIdMessagesMessageIdGet$Params {
  chat_id: number;
  message_id: number;
}

export function getChatMessageChatsChatIdMessagesMessageIdGet(http: HttpClient, rootUrl: string, params: GetChatMessageChatsChatIdMessagesMessageIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<ChatMessageResponse>> {
  const rb = new RequestBuilder(rootUrl, getChatMessageChatsChatIdMessagesMessageIdGet.PATH, 'get');
  if (params) {
    rb.path('chat_id', params.chat_id, {});
    rb.path('message_id', params.message_id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ChatMessageResponse>;
    })
  );
}

getChatMessageChatsChatIdMessagesMessageIdGet.PATH = '/chats/{chat_id}/messages/{message_id}';
