/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface GetChatAttachmentChatsChatIdAttachmentsAttachmentIdGet$Params {
  chat_id: number;
  attachment_id: string;
}

export function getChatAttachmentChatsChatIdAttachmentsAttachmentIdGet(http: HttpClient, rootUrl: string, params: GetChatAttachmentChatsChatIdAttachmentsAttachmentIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<any>> {
  const rb = new RequestBuilder(rootUrl, getChatAttachmentChatsChatIdAttachmentsAttachmentIdGet.PATH, 'get');
  if (params) {
    rb.path('chat_id', params.chat_id, {});
    rb.path('attachment_id', params.attachment_id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<any>;
    })
  );
}

getChatAttachmentChatsChatIdAttachmentsAttachmentIdGet.PATH = '/chats/{chat_id}/attachments/{attachment_id}';
