/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ChatMessagesPageResponse } from '../../models/chat-messages-page-response';

export interface GetChatMessagesChatsChatIdMessagesGet$Params {
  chat_id: number;
  before_id?: (number | null);
  limit?: number;
}

export function getChatMessagesChatsChatIdMessagesGet(http: HttpClient, rootUrl: string, params: GetChatMessagesChatsChatIdMessagesGet$Params, context?: HttpContext): Observable<StrictHttpResponse<ChatMessagesPageResponse>> {
  const rb = new RequestBuilder(rootUrl, getChatMessagesChatsChatIdMessagesGet.PATH, 'get');
  if (params) {
    rb.path('chat_id', params.chat_id, {});
    rb.query('before_id', params.before_id, {});
    rb.query('limit', params.limit, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ChatMessagesPageResponse>;
    })
  );
}

getChatMessagesChatsChatIdMessagesGet.PATH = '/chats/{chat_id}/messages';
