/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BodyUploadChatAttachmentChatsChatIdAttachmentsPost } from '../../models/body-upload-chat-attachment-chats-chat-id-attachments-post';
import { ChatAttachmentResponse } from '../../models/chat-attachment-response';

export interface UploadChatAttachmentChatsChatIdAttachmentsPost$Params {
  chat_id: number;
      body: BodyUploadChatAttachmentChatsChatIdAttachmentsPost
}

export function uploadChatAttachmentChatsChatIdAttachmentsPost(http: HttpClient, rootUrl: string, params: UploadChatAttachmentChatsChatIdAttachmentsPost$Params, context?: HttpContext): Observable<StrictHttpResponse<ChatAttachmentResponse>> {
  const rb = new RequestBuilder(rootUrl, uploadChatAttachmentChatsChatIdAttachmentsPost.PATH, 'post');
  if (params) {
    rb.path('chat_id', params.chat_id, {});
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ChatAttachmentResponse>;
    })
  );
}

uploadChatAttachmentChatsChatIdAttachmentsPost.PATH = '/chats/{chat_id}/attachments';
