/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { LotteryWinnerResultResponse } from '../models/lottery-winner-result-response';
export interface ActiveLotterySummaryResponse {
  admin_pubkey?: (string | null);
  created_at?: (string | null);
  draw_seconds?: number;
  end_date?: (string | null);
  execution_countdown_seconds?: number;
  id: number;
  lottery_pda?: (string | null);
  lottery_type?: string;
  max_total?: (number | null);
  next_pool_at?: (string | null);
  proceeding_purchases_started_at?: (string | null);
  second_phase_started_at?: (string | null);
  status: string;
  total_pool_sol?: number;
  vault_pda?: (string | null);
  winner_results?: Array<LotteryWinnerResultResponse>;
}
