/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ChatAttachmentResponse } from '../models/chat-attachment-response';
import { MessageAuthorResponse } from '../models/message-author-response';
import { ReplyPreviewResponse } from '../models/reply-preview-response';
export interface ChatMessageResponse {
  attachment?: (ChatAttachmentResponse | null);
  author: MessageAuthorResponse;
  chat_id: number;
  content: string;
  created_at: string;
  id: number;
  reply_to?: (ReplyPreviewResponse | null);
}
