/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ChatMessageResponse } from '../models/chat-message-response';
export interface ChatMessagesPageResponse {
  has_more: boolean;
  items: Array<ChatMessageResponse>;
}
