/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PricePointResponse } from '../models/price-point-response';
export interface CoinResponse {
  address: string;
  current_price: string;
  logo_url?: string;
  market_cap: string;
  name: string;
  price_history: Array<PricePointResponse>;
  symbol: string;
  volume_24h: string;
}
