/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CoinChartPointResponse } from '../models/coin-chart-point-response';
export interface CoinChartResponse {
  available?: boolean;
  change_pct?: (number | null);
  mint: string;
  minutes?: number;
  points?: Array<CoinChartPointResponse>;
  price_usd?: (number | null);
  venue?: (string | null);
}
