/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * A coin's red-flag check in this pool, once it has ended clean or flagged.
 *
 * Checked once, at the first commit to the coin in the pool
 * (`shared/coin_screening.py`). A coin with no check, or one that could not
 * be made, has none of this: the site then shows nothing.
 */
export interface CoinScreeningResponse {
  checked_at: string;
  levels?: {
[key: string]: string;
};
  missing?: Array<string>;
  on_curve?: (boolean | null);
  reasons?: Array<string>;
  source?: (string | null);
  status: 'clean' | 'flagged';
}
