/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * A chart point: epoch seconds and the price in dollars.
 */
export interface CoinChartPointResponse {
  p: number;
  t: number;
}
