/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateLotteryRequest {
  end_date?: (string | null);
  lottery_type?: string;
  max_total?: (number | null);
  name: string;
}
