/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateBetRequest {
  lottery_id?: (number | null);
  lottery_type?: (string | null);
  meme_coin_address: string;
  sol_amount: number;
  tx_signature: string;
  wallet_address: string;
}
