/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { LotteryArchiveItemResponse } from '../models/lottery-archive-item-response';
export interface LotteryArchiveListResponse {
  items?: Array<LotteryArchiveItemResponse>;
  lottery_type?: string;
  window_days?: number;
}
