/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { LotteryArchiveEntryResponse } from '../models/lottery-archive-entry-response';
export interface LotteryArchiveItemResponse {
  close_reason?: (string | null);
  ended_at: string;
  ended_at_source: string;
  entries?: Array<LotteryArchiveEntryResponse>;
  id: number;
  initialize_abandoned_at?: (string | null);
  initialize_abandoned_error?: (string | null);
  lottery_pda?: (string | null);
  lottery_type?: string;
  started_at: string;
  status: string;
  total_pool_sol?: number;
}
