/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface LotteryCycleControlResponse {
  enabled: boolean;
  hype_launch_at?: (string | null);
  lottery_type: string;
  stop_requested_at?: (string | null);
  updated_at?: (string | null);
}
