/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface LotteryArchiveEntryResponse {
  mint: string;
  name: string;
  rank: number;
  ticker: string;
  total_solana_bet: number;
  won_sol?: (number | null);
}
