/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { LotteryWinnerResultResponse } from '../models/lottery-winner-result-response';

/**
 * Everything an outsider can check a round's draw with.
 *
 * The fields are named so that the script in the public repository has nothing
 * to guess: the commitment and its preimage, the source of the randomness and
 * the fingerprint of the shares algorithm, and the result.
 */
export interface LotteryVerificationResponse {
  admin_account?: (string | null);
  algorithm_source?: string;
  lottery_account?: (string | null);
  lottery_id: number;
  lottery_type: string;
  network: string;
  program_id?: (string | null);
  randomness_account?: (string | null);
  randomness_source?: string;
  status: string;
  vault_account?: (string | null);
  vrf_algorithm_hash?: (string | null);
  vrf_seed?: (string | null);
  weights_hash_onchain?: (string | null);
  weights_hash_recomputed?: (string | null);
  weights_match?: (boolean | null);
  weights_payload?: (string | null);
  winner_results?: Array<LotteryWinnerResultResponse>;
}
