/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CoinResponse } from '../models/coin-response';
export interface LotteryEntryResponse {
  bet_count: number;
  burn_bps_avg?: number;
  coin: CoinResponse;
  lottery_id: number;
  lottery_type?: string;
  rank: number;
  total_solana_bet: string;
}
