/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { LotteryCycleControlResponse } from '../models/lottery-cycle-control-response';
export interface LotteryCycleControlsResponse {
  items?: Array<LotteryCycleControlResponse>;
}
