/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface MintAllowTokenResponse {
  dex_id?: (string | null);
  dex_liquidity_check_unverified?: boolean;
  dex_liquidity_pool_count?: number;
  has_dex_liquidity?: boolean;
  is_pumpfun_mint: boolean;
  liquidity_usd?: (number | null);
  market_cap_usd?: (number | null);
  mint_address: string;
  network_type: string;
  pair_url?: (string | null);
  price_change_24h?: (number | null);
  price_usd?: (number | null);
  token_image_url?: (string | null);
  token_name?: (string | null);
  token_symbol?: (string | null);
  volume_24h_usd?: (number | null);
}
