/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * One coin in my round: how much I put in and what became of it.
 */
export interface MyCommitCoinResponse {
  drawn_sol?: (number | null);
  logo_url?: (string | null);
  mint: string;
  my_commits: number;
  my_sol: number;
  name: string;
  pool_sol: number;
  signatures?: Array<string>;
  ticker: string;
}
