/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { MyCommitRoundResponse } from '../models/my-commit-round-response';
export interface MyCommitsResponse {
  rounds?: Array<MyCommitRoundResponse>;
  total_sol: number;
}
