/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { MyCommitCoinResponse } from '../models/my-commit-coin-response';

/**
 * A round I took part in.
 */
export interface MyCommitRoundResponse {
  coins?: Array<MyCommitCoinResponse>;
  created_at?: (string | null);
  end_date?: (string | null);
  lottery_id: number;
  lottery_type: string;
  my_sol: number;
  pool_sol: number;
  status: string;
  wallets?: Array<string>;
}
