/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SmartContractEventResponse } from '../models/smart-contract-event-response';
export interface PagedSmartContractEventResponse {
  items: Array<SmartContractEventResponse>;
  total_count: number;
}
