/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { LotteryResponse } from '../models/lottery-response';
export interface PagedLotteryResponse {
  items: Array<LotteryResponse>;
  total_count: number;
}
