/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UserResponse } from '../models/user-response';
export interface PagedUserResponse {
  items: Array<UserResponse>;
  total_count: number;
}
