/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * What the admin browser needs to sign `start_second_phase` itself.
 *
 * The request seed is derived here and never in the browser: the same
 * derivation already exists in the program and in the worker, and a third
 * copy in TypeScript is one more place for the three to disagree.
 */
export interface Phase2AccountsResponse {
  lottery_pda: string;
  recent_slothashes: string;
  seed_slot: number;
  vrf_network_state: string;
  vrf_program: string;
  vrf_request: string;
  vrf_treasury: string;
  weights_hash: string;
}
