/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Phase2RevealResponse {
  randomness_account: string;
  reveal_signature: string;
  value_hex?: (string | null);
}
