/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * RFC 7807 Problem Details for HTTP APIs
 */
export interface ProblemDetails {
  detail: string;
  instance?: (string | null);
  status: number;
  title: string;
  type?: string;
}
