/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Where a coin's burn stands. Raw token units as strings: they do not fit a double.
 */
export interface PurchaseFeedCoinBurnResponse {
  blocked_reason?: (string | null);
  bought_raw: string;
  burned_raw: string;
  owed_raw: string;
  supply_at_end?: (string | null);
  supply_at_start?: (string | null);
}
