/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PurchaseFeedBurnResponse } from '../models/purchase-feed-burn-response';
import { PurchaseFeedCoinResponse } from '../models/purchase-feed-coin-response';
import { PurchaseFeedDeliveryResponse } from '../models/purchase-feed-delivery-response';
import { PurchaseFeedItemResponse } from '../models/purchase-feed-item-response';
import { PurchaseFeedRefundResponse } from '../models/purchase-feed-refund-response';
export interface PurchaseFeedResponse {
  available?: boolean;
  bought_sol?: number;
  burns?: Array<PurchaseFeedBurnResponse>;
  coins?: Array<PurchaseFeedCoinResponse>;
  completed_purchases?: number;
  deliveries?: Array<PurchaseFeedDeliveryResponse>;
  fallback_ends_at?: (string | null);
  finished?: boolean;
  lottery_id: number;
  phase?: string;
  planned_purchases?: number;
  purchases?: Array<PurchaseFeedItemResponse>;
  refunds?: Array<PurchaseFeedRefundResponse>;
  target_sol?: number;
}
