/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PurchaseFeedCoinResponse } from '../models/purchase-feed-coin-response';
import { PurchaseFeedItemResponse } from '../models/purchase-feed-item-response';
export interface PurchaseFeedResponse {
  available?: boolean;
  bought_sol?: number;
  coins?: Array<PurchaseFeedCoinResponse>;
  completed_purchases?: number;
  finished?: boolean;
  lottery_id: number;
  planned_purchases?: number;
  purchases?: Array<PurchaseFeedItemResponse>;
  target_sol?: number;
}
