/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PurchaseFeedBurnResponse {
  at: string;
  decimals?: (number | null);
  logo_url?: (string | null);
  mint: string;
  name: string;
  raw_amount: string;
  signature: string;
  symbol: string;
}
