/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PurchaseFeedCoinResponse {
  bought_sol: number;
  completed_purchases: number;
  logo_url?: (string | null);
  mint: string;
  name: string;
  planned_purchases: number;
  status: string;
  symbol: string;
  target_sol: number;
}
