/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PurchaseFeedCoinBurnResponse } from '../models/purchase-feed-coin-burn-response';
export interface PurchaseFeedCoinResponse {
  bought_sol: number;
  burn?: (PurchaseFeedCoinBurnResponse | null);
  burn_bps?: number;
  completed_purchases: number;
  decimals?: (number | null);
  logo_url?: (string | null);
  mint: string;
  name: string;
  planned_purchases: number;
  status: string;
  symbol: string;
  target_sol: number;
}
