/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Unspent SOL going back to the people behind a coin: one transaction, one coin.
 */
export interface PurchaseFeedRefundResponse {
  at: string;
  logo_url?: (string | null);
  mint: string;
  name: string;
  recipients?: Array<string>;
  signature: string;
  sol_amount: number;
  symbol: string;
}
