/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * One purchase: it is visible on chain, so we return the signature as is.
 */
export interface PurchaseFeedItemResponse {
  at: string;
  logo_url?: (string | null);
  mint: string;
  name: string;
  signature: string;
  sol_amount: number;
  symbol: string;
  venue?: (string | null);
}
