/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * One delivery transaction: up to five wallets, one signature.
 */
export interface PurchaseFeedDeliveryResponse {
  at: string;
  decimals?: (number | null);
  logo_url?: (string | null);
  mint: string;
  name: string;
  raw_amount: string;
  recipients?: Array<string>;
  signature: string;
  symbol: string;
}
