/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Says nothing about whether the address has an account.
 */
export interface ResendConfirmationResponse {
  message: string;
}
