/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RetryRandomnessCheckResponse {
  can_retry_now: boolean;
  lottery_id: number;
  max_vrf_retries: number;
  next_retry_available_in_seconds: number;
  onchain_status?: (string | null);
  onchain_vrf_called?: (boolean | null);
  onchain_vrf_ready_ts?: (number | null);
  onchain_vrf_retry_count?: (number | null);
  randomness_account?: (string | null);
  randomness_reveal_slot?: (number | null);
  randomness_revealed?: (boolean | null);
  reasons: Array<string>;
  should_call_retry_randomness: boolean;
}
