/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { RunPurchasesToken } from '../models/run-purchases-token';
export interface RunPurchasesPayload {
  lotteryId: string;
  tokens: Array<RunPurchasesToken>;
}
