/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { RunPurchasesRecipient } from '../models/run-purchases-recipient';
export interface RunPurchasesToken {
  mint: string;
  recipients: Array<RunPurchasesRecipient>;
  totalSol: number;
}
