/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RunPurchasesRecipient {
  amount: number;
  amountLamports?: (string | null);
  burnBps?: (number | null);
  burnWeight?: (string | null);
  publickey: string;
}
