/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { RunPurchasesPayload } from '../models/run-purchases-payload';
export interface RunPurchasesResponse {
  lottery_id: number;
  offchain_response: {
};
  payload: RunPurchasesPayload;
}
