/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SmartContractEventResponse {
  created_at: string;
  data: ({
} | null);
  event_name: string;
  id: number;
  raw_logs: (Array<string> | null);
  signature: (string | null);
}
