/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * One commit that asked for a burn, as the chain has it.
 */
export interface VerificationBurnBetResponse {
  burn_bps: number;
  signature?: (string | null);
  sol: number;
  wallet: string;
}
