/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { VerificationBurnBetResponse } from '../models/verification-burn-bet-response';
import { VerificationBurnTxResponse } from '../models/verification-burn-tx-response';

/**
 * A coin some of whose backers asked for a burn, and how the burn went.
 *
 * Raw token units are decimal strings. `owed_raw` is floor(bought × the
 * coin's burn share); until the buying is over (`final`) it is owed for what
 * has been bought so far, because the promise is a share, not a number.
 */
export interface VerificationBurnResponse {
  bets?: Array<VerificationBurnBetResponse>;
  blocked_reason?: (string | null);
  bought_raw?: (string | null);
  burn_bps: number;
  burned_raw?: (string | null);
  coin_sol: number;
  decimals?: (number | null);
  final?: boolean;
  mint: string;
  name: string;
  owed_raw?: (string | null);
  supply_at_end?: (string | null);
  supply_at_start?: (string | null);
  symbol: string;
  transactions?: Array<VerificationBurnTxResponse>;
}
