/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface VrfPreviewResponse {
  budget_lamports: number;
  fee_bps: number;
  k: number;
  pool: number;
  seed_hex: string;
  targets: {
[key: string]: number;
};
  weights: {
[key: string]: number;
};
  wins: {
[key: string]: number;
};
}
