/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface WalletNonceResponse {
  chain: string;
  domain: string;
  expiration_time: string;
  issued_at: string;
  nonce: string;
  uri: string;
}
